language: node_js
node_js:
  - "stable"
  - "9"
  - "8"
  - "6"
  - "4"
sudo: false
script: npm test
matrix:
  allow_failures:
  - node_js: "stable"
  - node_js: "9"
after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
